name: Archive.org Saver
on:
    workflow_dispatch:
    schedule:
        - cron: "40 3 15 5,11 *"
jobs:
  Archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install Dependencies
        run: |
          cd ~
          printf "${{ secrets.ARCHIVE_ORG_AUTH }}" > archive.org.auth
          pip install tqdm
      - name: Run the Site Archiver
        run: |
          python scripts/archive_site.py
