name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
        BUILD_DIR: /home/runner/work/buddhist-uni.github.io/jekyll_build
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Normalize Unicode in the Previous Commit
        uses: buddhist-uni/normalized-unicode-action@v1
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.7
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: bash ./scripts/install-deps.bash
      - name: Install build requirements
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Build the site
        run: |
          mkdir $BUILD_DIR
          export RUBYOPT="--enable=yjit"
          ruby --version
          JEKYLL_ENV=production bundle exec jekyll build -d $BUILD_DIR --trace
          mv $BUILD_DIR/image_variants.bash ./scripts/
      - name: Purge CSS
        run: |
          shopt -s globstar
          npx purgecss -v --content $BUILD_DIR/**/*.html $BUILD_DIR/assets/js/*.js --css $BUILD_DIR/assets/css/main.css -o $BUILD_DIR/assets/css/purged-main.css
          test -s $BUILD_DIR/assets/css/purged-main.css
      - name: Push Img Deriver # Loving ripped off @cpina
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DERIVED_IMGS_SSH_KEY }}
          EMAIL: theopenbuddhistuniversity@gmail.com
        run: |
            mkdir --parents "$HOME/.ssh"
            DEPLOY_KEY_FILE="$HOME/.ssh/deploy_key"
            echo "${SSH_DEPLOY_KEY}" > "$DEPLOY_KEY_FILE"
            chmod 600 "$DEPLOY_KEY_FILE"
            SSH_KNOWN_HOSTS_FILE="$HOME/.ssh/known_hosts"
            ssh-keyscan -H "github.com" > "$SSH_KNOWN_HOSTS_FILE"
            export GIT_SSH_COMMAND="ssh -i "$DEPLOY_KEY_FILE" -o UserKnownHostsFile=$SSH_KNOWN_HOSTS_FILE"
            GIT_CMD_REPOSITORY="git@github.com:buddhist-uni/derived-imgs.git"
            CLONE_DIR=$(mktemp -d)
            git config --global user.email "$EMAIL"
            git config --global user.name "buddhist-uni"
            git clone --single-branch --depth 1 --branch main "$GIT_CMD_REPOSITORY" "$CLONE_DIR"
            cd "$CLONE_DIR"
            ls -la .
            mv $BUILD_DIR/gen_image_variants.bash ./
            git add .
            git status
            git commit -m "Lastest build script from build ${{ github.run_id  }}"
            git push "$GIT_CMD_REPOSITORY" --set-upstream main
      - name: Derived Img Cache
        uses: actions/cache@v3
        id: imgcache
        with:
          path: ${{ env.BUILD_DIR }}/derived_imgs
          key: imgderiver-v0-${{ hashFiles('./scripts/image_variants.bash') }}
      - name: Checkout Raw Imgs
        if: steps.imgcache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: buddhist-uni/imgs
          path: imgs
      - name: Checkout Big Imgs
        if: steps.imgcache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: buddhist-uni/original_size_imgs
          path: original_size_imgs
      - name: Generate Image Variants
        if: steps.imgcache.outputs.cache-hit != 'true'
        run: |
            convert --version
            mv imgs ../
            mv original_size_imgs ../
            bash ./scripts/image_variants.bash
      - name: Upload Build as Artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: ${{ env.BUILD_DIR }}
          retention-days: 62
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy the Artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
      - name: Invalidate the CloudFlare Cache
        shell: bash
        run: |
          echo "Hitting the CloudFlare API..."
          HTTP_RESPONSE=$(curl -sSX POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache" -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" -H "Content-Type:application/json" -w "HTTP_STATUS:%{http_code}" --data '{"purge_everything":true}')
          HTTP_BODY=$(echo "${HTTP_RESPONSE}" | sed -E 's/HTTP_STATUS\:[0-9]{3}$//')
          HTTP_STATUS=$(echo "${HTTP_RESPONSE}" | tr -d '\n' | sed -E 's/.*HTTP_STATUS:([0-9]{3})$/\1/')
          if [ "${HTTP_STATUS}" -eq "200" ]; then
            SUCCESS=$(echo ${HTTP_BODY} | python3 -c "import sys, json;print(json.load(sys.stdin)['success'])")
            if [ "${SUCCESS}" = "True" ]; then
              echo "Successfully purged!"
              echo "::group::Raw response"
              echo "${HTTP_BODY}"
              echo "::endgroup::"
              exit 0
            else
              echo "Unsuccessful purge!"
              echo "API response was:"
              echo "${HTTP_BODY}"
              exit 1
            fi
          else
            echo "Request failed. API response was ($HTTP_STATUS): "
            echo "${HTTP_BODY}"
            exit 1
          fi
